feat(tel): add scripts from PATH
Add tel- scripts from last update, so they are properly tracked. I only
track ~/.tel, but it also adds scripts to $PREFIX/bin

diff --git a/Configs/termux/tel/bin/tel-app b/Configs/termux/tel/bin/tel-app
--- a/Configs/termux/tel/bin/tel-app
+++ b/Configs/termux/tel/bin/tel-app
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
-# TEL app launcher #
-
+### TEL app launcher ###
+version=0.3
+removing_app=false
 print_ERR_and_die(){
     # Error printing function
     printf "\e[38;5;1m[!]%s\n\e[m"\
@@ -13,30 +14,91 @@ show_help(){
             "tel-app [OPTIONS] [PATTERN]"\
             "__________________________"\
             "OPTIONS"\
-            "  -h   display this help message"\
-            "  -u   update app cache"
+            "  -h | --help   		display this help message"\
+            "  -i | --info   		show settings page for chosen app"\
+            "  -a | --activity      launch by activity path, without fzf"\
+            "  -l | --list-apps     list apps and thir launch activities"\
+            "  -L | --list-app-names list appps, only names"\
+            "  -r | --remove 		remove/uninstall chosen app"\
+            "  -u | --update-cache  update app cache"
 }
 
 update_cache(){
-    # Android Black Magic
     printf  "\e[38;5;2m Launcher\e[m: \e[38;5;1mUpdating app cache...%s\n\e[m"
     am broadcast --user 0 \
          --es com.termux.app.reload_style apps-cache \
          -a com.termux.app.reload_style com.termux > /dev/null
 }
 
-main(){
+launch() {
+    app_name="$1"
+    activity_path="$2"
+    printf  "\e[38;5;2m Launching\e[m %s\n"\
+        "$app_name - $activity_path"
+    # Launch the app
+    am start -n "$activity_path" --user 0 > /dev/null 2>&1
+}
+
+list_apps() {
+    IFS=$'\n' apps=( "$(cat ~/.apps | sort)" )
+        for app in ${apps[@]}; do
+            IFS='|' read app_name activity package junk <<< "$app"
+            if [ "$1" == "-L" ]; then
+                echo $app_name
+            else
+                echo $app_name - $activity
+            fi
+    done
+}
+
+main() {
     cachefile="$HOME/.apps"
     app_namefile="$HOME/.app_names"
+    show_info_page="false"
     case "$1" in
+        -v | --version)
+    		printf  "\e[38;5;2m Launcher\e[m: \e[38;5;1mversion $version"
+		exit 0
+	;;
+        -i | --info)
+		shift
+        	show_info_page="true"
+        ;;
         # Update the app list
         # Incase a new app has been installed
-        -u)
-            update_cache
-            exit 0
+        -u | --update-cache)
+        	update_cache
+        	exit 0
         ;;
+        -r | --remove)
+		shift
+		removing_app=true
+	    ;;
+        -l | --list-apps)
+            list_apps
+            exit 0
+            ;;
+        -L | --list-app-names)
+            list_apps -L
+            exit 0
+            ;;
+        -a | --activity)
+            shift
+            if [ $# -eq 0 ]; then
+                echo Error: No argumenrs given
+                exit 1
+            elif [ $# -eq 1 ]; then
+                IFS='|' read name junk <<< "$(cat ~/.apps | grep "$1")"
+                    launch "$name" "$1"
+            elif [ $# -eq 2  ]; then
+                    launch "$1" "$2"
+            else
+                echo Error: too many arguments
+            fi
+            exit 0
+            ;;
         # Display the help message
-        -h)
+        -h | --help)
             show_help
             exit 0
         ;;
@@ -47,7 +109,7 @@ main(){
     # fuzzy search in $app_namefile to get the app code and app 
     # name in this format 
     # app_code | app_name
-    app_data=$(fzf -e --cycle --prompt=" Launch app: " --query="$*" --color=16 --select-1 -0 < "$app_namefile")
+    app_data=$(fzf -e --prompt=" Choose app: " --query="$*" --color=16 --select-1 -0 < "$app_namefile")
     case "$?" in
         # No app found
         "1"  )
@@ -58,7 +120,7 @@ main(){
         "130")
             return 1
         ;;
-esac
+    esac
     # get the app code
     app_code=$( echo "$app_data" | cut -d "|" -f1) 
     # get the app name
@@ -69,10 +131,31 @@ esac
 
     # get the activity name
     activity=$( grep "$app_code" "$cachefile" | cut -d "|" -f2 )
-    printf  "\e[38;5;2m Launching\e[m %s\n"\
-            "$app_name - $activity"
-
-    # Laucnh the app
-    am start -n "$activity" --user 0 > /dev/null 2>&1
+    
+    if [ "$removing_app" == "true" ] ; then
+    	printf  "\e[38;5;2m Launcher\e[m: \e[38;5;1mUninstall app '$app_name'? y/N\n\e[m"
+	read response
+	if [ "$response" == y ] ; then
+		activity=$(echo "$activity" | cut -d "/" -f1)
+		uninstalled=$(su -c pm uninstall $activity > /dev/null)
+		if [ "$?" == 0 ] ; then
+			printf "\e[38;5;2m Launcher\e[m: \e[38;5;1m'$app_name' was uninstalled\e[m\e\n"
+			update_cache
+		else
+			printf "\e[33;5;2m Launcher:\e[m error removing $app_name"
+			exit 1
+		fi
+	else
+		exit 0
+	fi
+	exit 0
+    elif [ "$show_info_page" == "true" ] ; then
+    	printf  "\e[33;5;2m Launching\e[m %s\n"\
+            "$app_name - app info page"
+	activity=$(echo "$activity" | cut -d "/" -f1)
+	am start -a android.settings.APPLICATION_DETAILS_SETTINGS "package:$activity" > /dev/null 2>&1
+    else
+        launch "$app_name" "$activity"
+    fi
 }
 main "$@"
diff --git a/Configs/termux/tel/bin/tel-backup b/Configs/termux/tel/bin/tel-backup
--- a/Configs/termux/tel/bin/tel-backup
+++ b/Configs/termux/tel/bin/tel-backup
@@ -1,121 +1,344 @@
 #!/usr/bin/env bash
 # SealyJ
-# version 0.2
+# version 0.3
+source tel-helpers
 today=$(date +"%m_%d_%Y")
+datetime=$(date +"%H_%M")
 temp_storage=~/../usr/tmp
 backup_location=~/storage/shared/tel/backup
+version=0.1
+
+show_help(){
+    printf  "%s\n"\
+            "tel-backup [OPTIONS]"\
+            "__________________________"\
+            "OPTIONS"\
+            "  -h | --help   		display this help message"\
+            "  -v | --version  		display version"\
+            "  --remove 			remove backups"\
+            "  -r | --restore 		restore from backups"\
+            "  -b | --backup  		create a backup"
+}
+spinner() {
+	# Spinner animation #
+	# line before calling spinner() must spawn bg process: eg echo hi;sleep 2 &;spinner	
+	# show working spinner
+	PID=$!
+	i=1
+	sp="/-\|"
+	echo -n ' '
+	while [ -d /proc/$PID ]
+	do
+		  echo -ne "\b${sp:i++%${#sp}:1}"
+		  sleep 0.1
+	done
+	echo -ne "\b${CHECK_MARK}" #remove last spinner
+	}
+
 
 check_folders(){
 if [ ! -d $temp_storage ] ; then
 	mkdir $temp_storage
 fi
-if [ ! -d ~/storage ] ; then
-	echo "Error - No access to phone storage"
-	echo "backups are made to /storage/emulated/0/tel, (this path is also accessible to TEL through ~/storage/shared/tel) if TEL hasn't been granted storage permissions, this will likely fail. Run termux-setup-storage to grant access"
-	echo program will exit.. && exit
-fi
-if [ ! -d ~/storage/shared/tel/backup ] ; then
-	mkdir -p $backup_location 
-fi
-if [ ! -d "$backup_location/$today" ] ; then
-	mkdir $backup_location/$today && printf "\e[38;5;2m Backup\e[m%s: created backup folder at: $backup_location/$today \n"
-fi
-}
+	if [ ! -d ~/storage ] ; then
+		printf "\e[38;5;2m Backup\e[m: "
+		echo "Error - No access to phone storage"
+		echo "backups are made to /storage/emulated/0/tel, (this path is also accessible to TEL through ~/storage/shared/tel) if TEL hasn't been granted storage permissions, this will likely fail. Run termux-setup-storage to grant access"
+		echo "program will exit.." && exit_utility
+	fi
+	if [ ! -d ~/storage/shared/tel/backup ] ; then
+		mkdir -p $backup_location 
+	fi
+	if [ ! -d "$backup_location" ] ; then
+		mkdir -p $backup_location && printf "\e[38;5;2m Backup\e[m: created backup folder at: %s" "$backup_location\n"
+	fi
+	}
 
-make_backup(){
-while true
-do
-	read -p "This will overwrite any previous backups made the same day are you sure you want to continue? y/N : " answer
-case $answer in
-	[yY]* )
+	make_backup(){
+	while true
+	do
+		printf "\e[38;5;2m Backup\e[m: "
+		read -p "This operation may overwrite previous backups made in the last minute, do you wish to continue? y/N : " answer
+	case $answer in
+		[yY]* )
+			check_folders  #create dirs if missing
+			echo -e "\n\e[38;5;2m Backup\e[m: Name backup files? (blank to skip): "
+			read answer
+			if [ ! -z "$answer" ] ; then
+				user_custom_name="$answer-"
+			else 
+				user_custom_name=""
+			fi
+			# Termux packages #
+			echo -ne "\n\e[38;5;2m Backup\e[m: creating installed pkgs archive "
+			rm -rf $TMPDIR/tel-backup/tmp
+			mkdir -p $TMPDIR/tel-backup/tmp
+			cd $TMPDIR/tel-backup/tmp
+			echo -n "user_pkgs" > .restore_path
+			(pkg list-installed 2>/dev/null | cut -d'/' -f 1 > user_pkgs.txt 2>&1)
+			(pip list --format freeze 2>/dev/null 2>/dev/null | cut -d'=' -f 1 > pip_user_pkgs.txt 2>&1)
+			sed -i '1d' user_pkgs.txt # delete first 'Listing done' line from apt output
+			tar -v -c -z -f $backup_location/$today-$datetime${user_custom_name}user_pkgs.tar.gz . >&/dev/null &
+			spinner
+			cd $TMPDIR 
+			rm -rf tel-backup/tmp
 		
-		check_folders  #create dirs if missing
+			# ~/.config #
+			echo -ne "\n\e[38;5;2m Backup\e[m: compressing pkg configs "
+			cd ~/.config
+			rm -rf .restore_path
+			echo -n "$(pwd)" > .restore_path
+			tar -v -c -z -f $backup_location/$today-$datetime${user_custom_name}pkg_config.tar.gz . >&/dev/null &
+			spinner
+			rm -rf .restore_path	
 
-		printf "\e[38;5;2m Backup\e[m%s: creating installed pkgs list...\n"
-		(apt list --installed > $backup_location/$today/userpkgs.txt > /dev/null 2>&1)
-		printf "\e[38;5;2m Backup\e[m%s: backing up configs...\n"
-		tar czf $backup_location/$today/userconfs_$backup_name.tar.gz ~/.tel/configs >&/dev/null
-		printf "\e[38;5;2m Backup\e[m%s: backing up termux settings...\n"
-		tar czf $backup_location/$today/termux_$backup_name.tar.gz ~/.termux >&/dev/null
-		printf "\e[38;5;2m Backup\e[m%s: backing up TEL user data...\n"
-		tar czf $backup_location/$today/userdata_$backup_name.tar.gz ~/.tel/data >&/dev/null & # last must be child process
+			# SSH data #
+			if [ -d ~/.ssh ] ; then
+				echo -ne "\n\e[38;5;2m Backup\e[m: compressing ssh data "
+				cd ~/.ssh
+				rm -rf .restore_path
+				echo -n "$(pwd)" > .restore_path
+				tar -v -c -z -f $backup_location/$today-$datetime${user_custom_name}ssh.tar.gz . >&/dev/null &
+				spinner
+				rm -rf .restore_path
+			fi
+
+			# wal colors #
+			if [ -d ~/.cache/wal ] ; then
+				echo -ne "\n\e[38;5;2m Backup\e[m: compressing color data "
+				cd ~/.cache/wal
+				rm -rf .restore_path
+				echo -n "$(pwd)" > .restore_path
+				tar -v -c -z -f $backup_location/$today-$datetime${user_custom_name}colors.tar.gz . >&/dev/null &
+				spinner
+				rm -rf .restore_path
+			fi
+
+		## wallpapers #
+		#echo -ne "\n\e[38;5;2m Backup\e[m: compressing wallpapers "
+		#cd ~/.wallpapers
+		#rm -rf .restore_path
+		#echo -n "$(pwd)" > .restore_path
+		#tar -v -c -z -f $backup_location/$today-$datetime${user_custom_name}wallpapers.tar.gz . >&/dev/null &
+		#spinner
+		#rm -rf .restore_path
+
+		# themes #
+		echo -ne "\n\e[38;5;2m Backup\e[m: compressing themes "
+		cd ~/.tel/theme/inactive
+		rm -rf .restore_path
+		echo -n "$(pwd)" > .restore_path
+		tar -v -c -z -f $backup_location/$today-$datetime${user_custom_name}themes.tar.gz . >&/dev/null &
+		spinner
+		rm -rf .restore_path
+
+		# Termux settings #
+		echo -ne "\n\e[38;5;2m Backup\e[m: compressing termux settings "
+		cd ~/.termux
+		rm -rf .restore_path
+		echo -n "$(pwd)" > .restore_path
+		tar -v -c -z -f $backup_location/$today-$datetime${user_custom_name}termux.tar.gz --exclude='shell' . >&/dev/null &
+		spinner
+		rm -rf .restore_path
+
+		# TEL CONFIGS #
+		echo -ne "\n\e[38;5;2m Backup\e[m: compressing TEL configs "
+		cd ~/.tel/configs
+		rm -rf .restore_path
+		echo -n "$(pwd)" > .restore_path
+		tar -v -c -z -f $backup_location/$today-$datetime${user_custom_name}tel_confs.tar.gz . >&/dev/null &
+		spinner
+		rm -rf .restore_path
+
+		# TEL DATA #
+		echo -ne "\n\e[38;5;2m Backup\e[m: compressing TEL user data "
+		cd ~/.tel/data
+		rm -rf .restore_path >&/dev/null
+		echo -n "$(pwd)" > .restore_path
+		tar -v -c -z -f $backup_location/$today-$datetime${user_custom_name}tel_data.tar.gz . >&/dev/null &
+		spinner
+		rm -rf .restore_path
 		
-		#show working spinner
-		PID=$!
-		i=1
-		sp="/-\|"
-		echo -n ' '
-		while [ -d /proc/$PID ]
-		do
-			  printf "\b${sp:i++%${#sp}:1}"
-			  sleep 0.1
-		done
-		echo -ne '\r' #remove last spinner
-		printf "\e[38;5;2m Backup\e[m%s: completed\n"
+		echo -ne "\n\e[38;5;2m Backup\e[m: completed! \n "
 		break;;
 
-	[nN]* ) exit;;
+	[nN]* ) exit_utility;;
 	* )     echo "options are y or n...";;
-esac
-done
+	esac
+	done
 
 }
 
+	
 restore_backup(){
-	printf "\e[38;5;2m Restore\e[m%s: loading data...\n"
-	cd $backup_location && ls -d | fzf
+	echo -ne "\e[38;5;2m Restore\e[m: loading data...\n"
+	cd $backup_location
+	restore_files_chosen=$(fd --type f | fzf -m -d -e --cycle --color=16 --prompt="Select archive(s) (with tab key) to restore: ")
+	[[ -z "$restore_files_chosen" ]] && exit 1
+	#generate array with fzf multiselect output
+	IFS=$'\n' read -d '' -r -a selected_archives <<<"$restore_files_chosen"
+	#echo "selected_arch array = ${selected_archives[@]}"
+	echo -e "\r\e[38;5;2m Restore\e[m: you have selected; "
+	for archive in "${selected_archives[@]}"
+	do
+		echo " -> $archive"
+	done	
+	echo -e "\r\e[38;5;2m Restore\e[m: Are you sure you wish to restore file(s) y/N : "
+	read -r answer
+	case $answer in
+		[yY]* )
+			for archive in "${selected_archives[@]}"
+			do
+				cd $backup_location || exit 1
+				rm -r tmp > /dev/null 2>&1 #rm any partial failure
+				mkdir tmp > /dev/null 2>&1
+				cd tmp
+				tar -x -U -f $backup_location/$archive --keep-directory-symlink
+				restore_path=$(cat .restore_path)
+
+				if [ "$restore_path" == "user_pkgs" ] ; then
+					install_pkgs
+				else
+					if [ ! -d $restore_path ] ; then
+						# if restore path missing make it
+						mkdir $restore_path
+					fi
+					echo
+					echo -ne "\e[38;5;2m Restoring\e[m: from archive: $archive -> $restore_path "
+					cp -rf * $restore_path &
+					#run_spinner #move to func
+					PID=$!
+					i=1
+					sp="/-\|"
+					echo -n ' '
+					while [ -d /proc/$PID ]
+					do
+						echo -ne "\b${sp:i++%${#sp}:1}"
+						sleep 0.1
+					done
+					#echo -ne '\e[1A\033[2K\r' #remove last spinner
+					echo -ne "\e[1A\e[J\r\e[38;5;2m Restored\e[m: $archive -> $restore_path ${CHECK_MARK}"
+					echo 
+					sleep 0.1
+				fi
+
+				cd ..
+				rm -rf tmp > /dev/null 2>&1  # cleanup	
+			done
+			;;
+		[nN]* ) exit_utility;;
+		* )     echo "options are y or n...";;
+	esac
 }
 
+install_pkgs(){
+	printf "\e[38;5;2m Restore\e[m: restoring termux packages...\n"
+	pkg update -y
+	while IFS= read -r line; do
+		pkg_list_str="$pkg_list_str $line"
+	done < $backup_location/tmp/user_pkgs.txt
+	#echo "pkg_list_str = $pkg_list_str"
+	pkg install -y $pkg_list_str 2>/dev/null
+	printf "\e[38;5;2m Restore\e[m: restoring python packages...\n"
+	# Now Python packages!
+	while IFS= read -r line; do
+		pip_pkg_list_str="$pip_pkg_list_str $line"
+	done < $backup_location/tmp/pip_user_pkgs.txt
+	PIP_DISABLE_PIP_VERSION_CHECK=1 pip install --user $pip_pkg_list_str
+
+}
+
+remove_backups(){
+	while true
+	do
+		read -p "This action will delete ALL TEL backup archives from your device storage! Are you sure you wish to continue? yes/no : " answer
+		case $answer in
+			yes)
+				cd $backup_location || exit 1
+				rm -rf * && printf "\e[38;5;2m Backup & Restore\e[m: removed all old backup archives...\n"
+				break
+				;;
+			no)
+				exit_utility
+				;;
+			*)
+				echo "Please type yes or no..."
+				;;
+		esac
+	done
+}
 exit_utility(){
-	printf "\e[38;5;2m Backup & Restore\e[m%s: Exiting...\n"
+	printf "\e[38;5;2m Backup & Restore\e[m: Exiting...\n"
 	exit 0
 }
 
 main() {
 
-printf "\e[38;5;2m Backup & Restore\e[m%s\n"
+printf "\e[38;5;2m Backup & Restore\e[m\n"
 
-cmd=(dialog --separate-output --checklist "Backup & Restore options:" 22 76 16)
-options=(1 " Backup" 
-         2 "勒Restore" 
-         3 " Quit")
-choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
+HEIGHT=15
+WIDTH=40
+CHOICE_HEIGHT=4
+BACKTITLE="tel-backup"
+TITLE="Backup & Restore"
+MENU="Choose one of the following options:"
+
+OPTIONS=(1 " Backup"
+         2 " Restore"
+         3 " Quit"
+         4 " Remove Backups")
+
+CHOICE=$(dialog --clear \
+                --backtitle "$BACKTITLE" \
+                --title "$TITLE" \
+                --menu "$MENU" \
+                $HEIGHT $WIDTH $CHOICE_HEIGHT \
+                "${OPTIONS[@]}" \
+                2>&1 >/dev/tty)
+
 clear
-for choice in $choices
-do
-    case $choice in
+case $CHOICE in
         1)
-            echo "First Option"
 	    make_backup
             ;;
         2)
-            echo "Second Option"
 	    restore_backup
             ;;
         3)
-            echo "Third Option"
 	    exit_utility
             ;;
-        *)
-            echo "not an option fool D:"
-            ;;
-    esac
-done
-#show menu
-#PS3="Enter a number: "
-#select option in ' Backup' '勒Restore' ' Quit' ; do
-#  case $opt in
-#	 Backup)
-#		make_backup;;
-#	勒Restore)
-#		restore_backup;;
-#	 Quit)
-#		exit_utility;;
-#	*)
-#		echo "Invalid option $REPLY";;
-#  esac
-#done
+	4)
+	    remove_backups
+	    ;;
+esac
 }
-
-main $@
+if [ -n "$1" ] ; then
+	case "$1" in
+		-h | --help)
+			show_help
+			exit 0
+			;;
+		-v | --version)
+			printf  "\e[38;5;2mBackup & Restore\e[m: \e[38;5;1mversion %s" "$version"
+			exit 0
+			;;
+		-b | --backup)
+			make_backup
+			exit 0
+			;;
+		-r | --restore)
+			restore_backup
+			exit 0
+			;;
+		--remove)
+			remove_backups
+			exit 0
+			;;
+		*)	
+			printf  "\e[38;5;2mBackup & Restore\e[m: \e[38;5;1moption not recognised"
+			exit 1
+esac
+	else
+		main $@
+	fi
 
diff --git a/Configs/termux/tel/bin/tel-dialer b/Configs/termux/tel/bin/tel-dialer
--- a/Configs/termux/tel/bin/tel-dialer
+++ b/Configs/termux/tel/bin/tel-dialer
@@ -1,22 +1,17 @@
 #!/usr/bin/env bash
-#
-# TEL caller
-#_______________________________________________________________________
+# TEL Dialer #
+# ---------- # 
+# sealyj
+# sidd_dino 
 
-# Usage
-# call [OPTIONS] [PATTERN]
-# call -h
-# call -u
-# call blah
-# call 2121821218
-
-# location of the contacts folder
+version=0.2
+# location of the contacts file
 contactsfile="$HOME/.tel/data/.contacts";
 
 
 print_ERR_and_die() {
     # Error printing function
-    printf "\e[38;5;1m[!]%s\n\e[m"\
+    printf "\e[33;5;1m[!]%s\n\e[m"\
            "$*" 1>&2
     exit 1
 }
@@ -27,7 +22,8 @@ show_help() {
                 "__________________________"\
                 "OPTIONS"\
 		"  -a 'name' 'number'	Add a new contact"\
-		"  -d			Display my number"\
+		"  -s			Share contacts number"\
+		"  -o			Output contacts number"\
                 "  -h   		Display this help"\
                 "  -u   		Update contact list"
         exit 0
@@ -41,7 +37,7 @@ update_contacts() {
     # file descriptor 9
     termux-contact-list > ~/.temp
 
-    # delay for 2 seconds   #what is this for? 
+    # delay for 2 seconds   
     read -rt "2" <> <(:) || :  
 
     while IFS=$'\n' read -sr line; do
@@ -58,8 +54,13 @@ update_contacts() {
 }
 
 add_contact(){
-	if [ $# -lt 2 ] ; then
-		printf  "\e[38;5;2m Dialer\e[m: \e[38;5;1mAdding a new contact: %s\n\e[m"
+	if [ $# -eq 2 ] ; then
+		printf  "\e[33;5;2m Dialer\e[m: Adding $2 to contacts \n"
+		add_contact_name=$2
+		echo 'Contact number:'
+		read add_contact_number
+	elif [ $# -eq 1 ] ; then
+		printf  "\e[33;5;2m Dialer\e[m: Adding a new contact \n"
 		echo 'Contact name:'
 		read add_contact_name
 		echo 'Contact number:'
@@ -68,8 +69,8 @@ add_contact(){
 		add_contact_name=$2
 		add_contact_number=$3
 	fi
-		am start -a android.intent.action.INSERT -t vnd.android.cursor.dir/contact -e name $add_contact_name -e phone $add_contact_number > /dev/null 2>&1
-	printf  "\e[38;5;2m Dialer\e[m: \e[38;5;1mAdded $add_contact_name to contacts%s\n\e[m"
+	am start -a android.intent.action.INSERT -t vnd.android.cursor.dir/contact -e name $add_contact_name -e phone $add_contact_number > /dev/null 2>&1
+	printf  "\e[33;5;2m Dialer\e[m: Added $add_contact_name to contacts%s\n"
 	touch ~/.dialer_flag
 	#update_contacts
 	exit 0
@@ -77,47 +78,92 @@ add_contact(){
 
 
 main() {
-    
+	request_output="false"
 	if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then
         	show_help 
+	elif [ "$1" == "-v" ] || [ "$1" == "--version" ] ; then
+		printf "\e[33;5;2m Dialer\e[m: version $version\n"
+
 	elif [ "$1" == "-a" ] || [ "$1" == "--add" ] ; then
 		add_contact "$@"
+	elif [ "$1" == "-o" ] || [ "$1" == "--output" ] ; then
+#		output_contact "$@"
+		request_output="true"
+		share="false"
+		shift
+	elif [ "$1" == "-s" ] || [ "$1" == "--share" ] ; then
+		request_output="true"
+		share="true"
+		shift
 	fi
 
     [[ ! -a "$contactsfile" || "$1" == '-u' || -f ~/.dialer_flag ]] && {
 	rm -f ~/.dialer_flag
-    	printf  "\e[38;5;2m Dialer\e[m: \e[38;5;1mGenerating contacts list...%s\n\e[m"
+    	printf  "\e[33;5;2m Dialer\e[m: Generating contacts list...\n"
 	update_contacts  # if contacts file missing - generate one
         [[ "$1" == '-u' ]] && exit 0
     }
-
     # fuzzy search in $contactsfile to get the number and
     # name in the format
     # Name | Number
-    contact=$(fzf -e --cycle --color=16 --prompt=" Call: " --query="$*" --select-1 -0 < "$contactsfile")
+	fzf_output=$(fzf --print-query --color=16 --prompt=" Contact: " --query="$*" --select-1 -0 < "$contactsfile")
     case "$?" in
-        	# No app found
+        	# No contact found
         "1"  )
-    		printf  "\e[38;5;2m Dialer\e[m: \e[38;5;1mContact not found%s\n\e[m"
+		if [ "$request_output" == "true" ] ; then
+			exit 1
+		fi
+		IFS=$'\n' read -d '' -r -a selected_contact <<< "$fzf_output"
+		if [ ${#selected_contact[@]} -gt 1 ] ; then #no match found assume output is printed number
+			unknown_number="${selected_contact[0]}"
+			contact="${selected_contact[1]}"
+		else
+			contact="${selected_contact[0]}"
+		fi
+		if [ ${#selected_contact[@]} -gt 0 ] ; then #no match found assume output is printed number
+		unknown_number=${selected_contact[0]}
+			if [ ${#unknown_number} -gt 2 ] ; then
+				#fail to get matching contact trying calling number
+				printf  "\e[33;5;2m Calling:\e[m %s\n"\
+				"[${unknown_number}]"
+				termux-telephony-call "${unknown_number}"
+			fi
+		fi
 		exit 1
         ;;
 
         # If Ctrl+C is used 
         "130")
-            return 1
+            exit 1
         ;;
 esac
+	IFS=$'\n' read -d '' -r -a selected_contact <<< "$fzf_output"
+	if [ ${#selected_contact[@]} -gt 1 ] ; then #no match found assume output is printed number
+		unknown_number="${selected_contact[0]}"
+		contact="${selected_contact[1]}"
+	else
+		contact="${selected_contact[0]}"
+	fi
+
     # get the contact's name
-    contact_name=$(echo "$contact" | cut -d "|" -f1) 
+    contact_name=$(echo "${contact}" | cut -d "|" -f1) 
     # get the contact's number
-    contact_number=$(echo "$contact" | cut -d "|" -f2 | tr -d '[:space:]')
-    printf  "\e[38;5;2m Calling:\e[m %s\n"\
-	    "$contact_name[$contact_number]"
+    contact_number=$(echo "${contact}" | cut -d "|" -f2 | tr -d '[:space:]')
     #kills the program if termux-telephony-call command is not available
     ( command -v termux-telephony-call >/dev/null 2>&1 ) || { 
-        print_ERR_and_die "termux-telephony-call not available, have you installed termux api?"
+        print_ERR_and_die "termux-telephony-call not found, have you installed termux-api?"
     }
-    termux-telephony-call "$contact_number"
+    if [ "$request_output" == "true" ] ; then
+	    echo "$contact_number"
+    elif [ "$share" == "true" ] ; then
+	    am start -a android.intent.action.SEND -t text/plain -e android.intent.extra.TEXT "$contact_number" > /dev/null 2>&1
+
+    else
+	    printf "\e[33;5;2m Calling:\e[m %s\n"\
+	    "$contact_name[$contact_number]"
+
+	termux-telephony-call "$contact_number"
+    fi
 }
 
 main "$@"
diff --git a/Configs/termux/tel/bin/tel-edit b/Configs/termux/tel/bin/tel-edit
--- a/Configs/termux/tel/bin/tel-edit
+++ b/Configs/termux/tel/bin/tel-edit
@@ -1,26 +1,112 @@
-#!/usr/bin/env bash
+#!/usr/bin/env zsh 
 # Edit applet for TEL
-# Version 1
+# Version 0.3
 # SealyJ 2020
-if [ "$1" == "-r" ] || [ "$1" == "--root" ] ; then
-	cd / 
+# requires: fzf bat nano 
+# optional: magisk su binary
+useroot=
+FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
+if [ "$1" = "-h" ] || [ "$1" = "--help" ] ; then
+	echo -e "Usage: tel-edit [options] [filename]
+	tel-edit			= interactive file picker
+	tel-edit configs		= display file picker with matches for configs
+	tel-edit -h			= show this help menu
+	tel-edit -r			= search from root directory with root privs
+	"
+	exit 0
+elif [ "$1" = "-r" ] || [ "$1" = "--root" ] ; then
+	shift
+	useroot=true
+	if [ ! -z $1 ] ; then
+		file_search="$@"
+	else
+		file_search=''
+	fi
+	selected_file=$('sudo fd . '/' -a  --type file --hidden --follow --exclude .git -E /proc -E /sys -E /dev -E /cache' | fzf --color=16 --query="$file_search" --prompt="  ROOT Edit with $EDITOR: ")
+	if [ ! -z $selected_file ] ; then
+		printf "\e[33;5;2m Editing\e[m%s file as root: $selected_file\n"
+		su -c "/data/data/com.termux/files/usr/bin/$EDITOR $selected_file"
+	else
+		exit 1
+	fi
+	exit 0
+else
+	FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
+	FZF_DEFAULT_OPTS="
+	--info=inline
+	--multi
+	--preview-window=up:60%:follow:sharp
+	--preview '([[ -f {} ]] && (termimage --size=35x35 {} || bat --italic-text=always --theme=base16 --style=full --color=always {} || bat -A {})) || ([[ -d {} ]] && (exa -T --level=1 {} | less)) || echo {} 2> /dev/null | head -200'
+	--prompt='∼ ' --pointer='>' --marker='✓'
+	--bind '?:toggle-preview'
+	--bind 'ctrl-a:select-all'
+	--bind 'ctrl-y:execute-silent(echo {+} | pbcopy)'
+	"
 fi
-export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
-[[ -z "$EDITOR" ]] && echo 'Please set a default $EDITOR' && exit 1
+
+show_help(){
+    printf  "%s\n"\
+            "Opens a file in your terminals text editor"\
+            "tel-edit [OPTIONS] [PATTERN]"\
+            "__________________________"\
+	    "OPTIONS"\
+            "  -h | --help	display this help message"\
+            "  -r | --root	use root privledged"
+}
+
+
 if [ -z $1 ] ; then
-	selected_file=$(fzf --cycle --color=16 --prompt="  Edit with $EDITOR: ")
+	selected_file=$(fd --hidden --follow --type f | fzf --color=16 --prompt="  Edit with $EDITOR: ")
 else
 	file_search=$(echo "$@")
-	selected_file=$(fzf -e --cycle --color=16 --query="$file_search" --prompt="  Edit with $EDITOR: " --select-1)
+	selected_file=$(fd --hidden --follow --type f | fzf --color=16 --query="$file_search" --prompt="  Edit with $EDITOR: " --select-1)
 fi
 
 if [ -z "$selected_file" ] ; then
-	# no file selected or cancel fzf selection, this is preferable as it allows user to correct typos in fzf prompt rather than giving 'file not found error' 
-	# printf "\e[38;5;2m Edit\e[m%s: Error - file not found "
+	# no file selected or cancel fzf = exit 1, this is preferable as it allows user to correct typos in fzf prompt rather than giving 'file not found error' 
+	# printf "\e[33;5;2m Edit\e[m%s: Error - file not found "
 	exit 1
 else
 	curr_dir=$(pwd)
-	printf "\e[38;5;2m Editing\e[m%s file: $curr_dir/$selected_file"
-	$EDITOR "$selected_file"
+	# manipulate history here
+	#print -S "$useroot $EDITOR $curr_dir/$selected_file"
+	printf "\e[33;5;2m Editing\e[m%s file: $curr_dir/$selected_file\n"
+	if [ -z $useroot ] ; then
+		#command_string="${EDITOR:-vi} $curr_dir/$selected_file"
+		command_string="${EDITOR:-vi} $curr_dir/$selected_file"
+	else
+		command_string="${EDITOR:-vi} $curr_dir/$selected_file"
+	fi
+	 #/home/sealyj/.oh-my-zsh/custom/plugins/zsh-hist/functions/hist f -1
+		#if [ "$SHELL" = $(which zsh) ] ; then
+		#tmploc=${TMPDIR:-/tmp}
+		# Prevent the specified history line from being saved.
+		#TEMP=$HISTFILE
+		#HISTFILE="$tmploc/zsh_hist"
+		#HISTORY_IGNORE="$(fc -ln -1 -1)"
+		#fc -W
+		  # Write out the history to file, excluding lines that match `$HISTORY_IGNORE`.
+		#delete oldest line
+		source ~/.zshrc
+		#sed -i '$d' $HISTFILE
+		insert_hist=": $EPOCHSECONDS:0;$command_string"
+		echo "$insert_hist" >> $HISTFILE
+		${EDITOR:-vi} $curr_dir/$selected_file
+	#	$command_string
+		#fc -AI
+		#fc -R
+		#fc -W 
+		#cp -f $TEMPHISTFILE $HISTFILE
+		#echo "$insert_hist" >> $HOME/.bash_history
+		# Dispose of the current history and read the new history from file.
+		#fc -p $HISTFILE $HISTSIZE $SAVEHIST
+
+		# TA-DA!
+		#print "Deleted '$HISTORY_IGNORE' from history."
+		#fc -f $tmploc
+		#echo "$insert_hist" >> $tmploc
+		#fc -r $HOME/.zsh_history
+	#elif [ "$SHELL" == $(which bash) ] ; then
+#	fi
 fi
 
diff --git a/Configs/termux/tel/bin/tel-open b/Configs/termux/tel/bin/tel-open
--- a/Configs/termux/tel/bin/tel-open
+++ b/Configs/termux/tel/bin/tel-open
@@ -1,56 +1,92 @@
 #!/usr/bin/env bash
-#cd ~/../ 
-export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
+# Open applet for TEL
+# Version 0.2
+# SealyJ 2020
+# requires: fzf fd 
+#if not on android also requires: perl-file-mimeinfo
+
+FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
+FZF_DEFAULT_OPTS="
+--info=inline
+--multi
+--preview-window=up:60%:follow:sharp
+--preview '([[ -f {} ]] && (termimage --size=35x35 {} || bat --theme=base16 --style=numbers --color=always {} || cat {})) || ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2> /dev/null | head -200'
+--color='hl:148,hl+:154,pointer:032,marker:010,bg+:237,gutter:008'
+--prompt='∼ ' --pointer='>' --marker='✓'
+--bind '?:toggle-preview'
+--bind 'ctrl-a:select-all'
+--bind 'ctrl-y:execute-silent(echo {+} | pbcopy)'
+"
 bookmarks_file=~/.tel/data/bookmarks 
 global_url=$2
-[[ -e $bookmarks_file ]] || echo 'https://t-e-l.github.io' > ${bookmarks_file} # create new list if none exists
+[[ -e $bookmarks_file ]] || (echo 'https://t-e-l.github.io' > ${bookmarks_file} ; echo -n 'https://wiki.termux.com/wiki/Main_Page' >> ${bookmarks_file}) # create new list if none exists)
+
+files_to_open=()
 show_help(){
     printf  "%s\n"\
             "Opens a file or link in external app"\
             "tel-open [OPTIONS] [PATTERN]"\
-            "__________________________"\                                              "OPTIONS"\
-            "  -h   display this help message"\
-            "  -u https://www.github.com  Open github in android browser"\
-            "  -u   Open url picker"
+            "__________________________"\
+			"OPTIONS"\
+            "  -h | --help  				Display this help message"\
+            "  -u | --url https://www.github.com 	Open github in android browser"\
+            "  -u | --url  				Open url picker"
 }
 open_url(){
    	if [ -n "$global_url" ]; then
 		url=$global_url
 	else
-		url=$(cat $bookmarks_file | fzf -e --cycle --color=16 --prompt=" Pick a URL to open with an android app:" --select-1)
+		url=$(cat $bookmarks_file | fzf -e --color=16 --prompt=" URL to open in app:" --select-1)
 	fi
 	if [ ! -z $url ] ; then
-	termux-open-url $url
-	printf "\e[38;5;2m Opening\e[m%s URL: $url" 
+		if [ $(uname -o) == 'Android' ] ; then
+			termux-open-url "$url"
+		else
+			xdg-open "$url"
+		fi	
+		printf "\e[33;5;2m Opening\e[m URL: %s" "$url"
 	else
 		exit 1
 	fi
 }
 
 if [ -z $1 ] ; then
-	selected_file=$(fzf --cycle --color=16 --prompt=" Open in app: ")
+	selected_files=$(fd --hidden --type f | fzf -m -d -e --color=16 --prompt="Select (tab key) Open: ")
+	IFS=$'\n' read -d '' -r -a files_to_open <<<"$selected_files"
 else
 	case "$1" in
-		-u) #open url in app instead of file
+		-u | --url) #open url in app instead of file
 		open_url
 		exit 0
 		;;
 		# Display the help message
-		-h)                                                                        show_help
+		-h | --help)                                                                        show_help
 		exit 0
 		;;
  	esac
 
 	file_search="$@"
-	selected_file="$(fzf -e --cycle --color=16 --query="$file_search" --prompt=" Open in app: " --select-1)"
+	# allow mutli selection save to array
+	selected_files=$(fd --hidden --follow --type f | fzf -m -d -e -q "$file_search" --color=16 --prompt="Select (tab key) Open: ")
+	IFS=$'\n' read -d '' -r -a files_to_open <<<"$selected_files"
 fi
 
-if [ -z "$selected_file" ] ; then
-#	echo 'No file chosen - Exiting...'
+
+if [ -z "${files_to_open}" ] ; then
+#	echo 'No files chosen - Exiting...'
 	exit 1
 else
 	curr_dir=$(pwd)
-	printf "\e[38;5;2m Opening\e[m%s file: $curr_dir/$selected_file"
-	termux-open "$selected_file" || echo "Couldn't open $selected_file"
+	echo -ne "\n\e[33;5;2m Opening\e[m: "
+	for filename in "${files_to_open[@]}"
+	do
+		echo -ne "$curr_dir/$filename\n"
+		if [ $(uname -o) == 'Android' ] ; then
+			termux-open "$filename" || echo "Couldn't open $selected_file"
+		else
+			(mimeopen -n "$filename" > /dev/null 2>&1) > /dev/null & 
+			#xdg-open "$selected_file" || echo "Couldn't open $selected_file"
+		fi
+	done	
 fi
 
diff --git a/Configs/termux/tel/bin/tel-theme b/Configs/termux/tel/bin/tel-theme
--- a/Configs/termux/tel/bin/tel-theme
+++ b/Configs/termux/tel/bin/tel-theme
@@ -1,7 +1,11 @@
 #!/usr/bin/env bash
-#cd ~/../ 
-export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
-wallpaper_folder=~/.wallpapers
+### TEL THEME MANAGER ###
+# sealyj 2021 #
+version=0.2
+FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
+wallpaper_folder=~/.tel/theme/active/wallpaper
+themes_folder=~/.tel/theme/inactive
+active_theme=~/.tel/theme/active
 
 show_help(){
     printf  "%s\n"\
@@ -9,87 +13,158 @@ show_help(){
             "tel-theme [OPTIONS] [PATTERN]"\
             "__________________________"\
 	    "OPTIONS"\
-            "  --install-theme   collect your current theme into a package ready for sharing"\
-            "  --create-theme   collect your current theme into a package ready for sharing"\
-            "  -h   display this help message"\
-            "  -f ~/mywallpaper.jpg  use supplied file"
+            "  -a | --apply		pick + apply a theme from your currently installed themes"\
+            "  -f | --file		auto-gen theme based on an image"\
+            "  -i | --install		install a TEL theme file package"\
+            "  -c | --create		collect and package current files into a theme file"\
+            "  -h | --help 		display this help message"
+}
+
+spinner() {
+	# Spinner animation #
+	# line before calling spinner() must spawn bg process: eg echo hi;sleep 2 &;spinner	
+	# show working spinner
+	PID=$!
+	i=1
+	sp="/-\|"
+	echo -n ' '
+	while [ -d /proc/$PID ]
+	do
+		echo -ne "\b${sp:i++%${#sp}:1}"
+		sleep 0.1
+	done
+	echo -ne "\b${CHECK_MARK}" #remove last spinner	
+}
+
+restart_tel(){
+	tel-restart
+	printf "\n\e[33;5;2m Theme\e[m%s press [Return] to restart + apply changes..\n"
+	read 
+	tel-restart
 }
 
 install_theme(){
-	echo 'this is WIP'
+	selected_theme=$(fd --ignore-case --absolute-path --type f | fzf -e --color=16 --query="$file_search" --prompt="Pick a theme to apply: " --select-1)
+	printf "\e[33;5;2m Theme\e[m%s installing theme file: $selected_theme\n"
+	cp -f $selected_theme $themes_folder
+	printf "\e[33;5;2m Theme\e[m%s installed theme: $selected_theme\n"
 }
 
 create_theme(){
-	mkdir $TEMP/tel-theme
-	cd $TEMP/tel-theme
-	cp ~/.tel/configs/theme.conf .
-	echo 'this is WIP'
+	printf "\e[33;5;2m Theme\e[m%s packaging current files into theme\n"
+	rm -rf $TMPDIR/tel-theme/* > /dev/null 2>&1
+	mkdir -p $TMPDIR/tel-theme/packaging/configs
+	mkdir -p $TMPDIR/tel-theme/packaging/wallpaper
+	mkdir -p $TMPDIR/tel-theme/packaging/termux
+	cd $TMPDIR/tel-theme/packaging
+	mkdir -p ~/.tel/theme/inactive >/dev/null 
+	cp ~/.tel/theme/active/wallpaper/*.jpg ./wallpaper/
+	cp ~/.tel/theme/active/colors.sh .
+	cp ~/.tel/configs/theme.conf ./configs/
+	cp ~/.termux/termux.properties ./termux
+	printf "\e[33;5;2m Theme\e[m%s Enter name for new theme: "
+	while [ -z "$new_theme_name" ] ; do
+		read new_theme_name
+	done
+	printf "\e[33;5;2m Theme\e[m%s Enter name of author: "
+	read author_theme_name
+	tar -v -c -z -f $themes_folder/${new_theme_name}.tar.gz . >&/dev/null &
+	spinner
+	printf "\e[33;5;2m Theme\e[m finished! \n theme to: $themes_folder/${new_theme_name}"
 }
 
+auto_theme(){
+	FZF_DEFAULT_OPTS="
+--info=inline
+--multi
+--preview-window=up:60%:follow:sharp
+--preview '([[ -f {} ]] && (termimage --size=35x35 {} || bat --theme=base16 --style=numbers --color=always {} || cat {})) || ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2> /dev/null | head -200'
+--prompt='∼ ' --pointer='>' --marker='✓'
+--bind '?:toggle-preview'
+--bind 'ctrl-a:select-all'
+--bind 'ctrl-y:execute-silent(echo {+} | pbcopy)'
+"
 
-if [ -z $1 ] ; then
-	cd $wallpaper_folder
-	selected_file=$(ls $wallpaper_folder | fzf -e --cycle --color=16 --prompt=" Pick a file to set as your wallpaper:")
-	options='-f'
-else
+	cd ~
+	if [ -z "$@" ] ; then
+		file_search="$@" 
+	else
+		file_search=".jpg"
+	fi
+	selected_file=$(fd --extension=jpg -e png --follow --absolute-path --hidden --type f | fzf --color=16 --query="$file_search" --prompt="Pick a image to theme from: " --select-1)
+	if [ -z $selected_file ] ; then
+		exit 1
+	fi
+	printf "\e[33;5;2m Theme\e[m%s extracting colorscheme from: $selected_file "
+	(wal -i "$selected_file" -n -q -s -t -e || (echo 'failed to get colors from file' ; exit 1)) &
+	spinner 
+	cp -rf ~/.cache/wal/colors.sh ~/.tel/theme/active/
+	mkdir -p ~/.tel/theme/active/wallpaper >/dev/null 2>&1
+	rm -rf ~/.tel/theme/active/wallpaper/* > /dev/null 2>&1
+	cp "$selected_file" ~/.tel/theme/active/wallpaper/
+	touch ~/.tel/theme/.flag
+	# add flag for setting wallpaper on reboot
+	~/.tel/scripts/apply_colors.sh # propagate colors
+	restart_tel
+}
+
+apply_theme(){
+	cd $themes_folder
+	file_search="$@"
+	selected_file=$(fd --exclude .git --ignore-case --type f | fzf -e --color=16 --query="$file_search" --prompt="Pick a theme to apply: " --select-1)
+	if [ -z $selected_file ] ; then
+		exit 1
+	fi
+	printf "\e[33;5;2m Theme\e[m%s applying: $selected_file "
+	#unzip
+	cd 
+	rm -rf $active_theme >/dev/null
+	mkdir $active_theme 
+	cd $active_theme
+	tar -x -U -f $themes_folder/$selected_file . &
+	spinner
+	touch ~/.tel/theme/.flag
+	# add flag for setting wallpaper on reboot
+	~/.tel/scripts/apply_colors.sh #propagate colors 
+	printf "\n\e[33;5;2m Theme\e[m%s finished applying: $selected_file "
+	restart_tel
+	}
+
+main(){
 	case "$1" in
-		--install-theme)
-		install_theme
-		exit 0
+		-v | --version)
+			printf "\n\e[33;5;2m Theme\e[m%s version: $version"
+			exit 0
 		;;
-		--create-theme)
-		create_theme
-		exit 0
+		-a | --apply)
+			shift
+			apply_theme
+			exit 0
 		;;
-		-f) #use file
-		options=$1
-		selected_file=$2
-		exit 0
+		-f | --file)
+			shift
+			auto_theme
+			exit 0
 		;;
-		-u) #use url
-		options=$1
-		selected_file=$2
-		exit 0
+		-i | --install)
+			install_theme
+			exit 0
+		;;
+		-c | --create)
+			create_theme
+			#read WAL wallpaper
+			exit 0
 		;;
 		# Display the help message
-		-h)                                                                        show_help
-		exit 0
+		-h | --help)
+			show_help
+			exit 0
 		;;
- 	esac
+		*)
+		show_help
+		exit 1
+		;;
+	esac
+}
 
-	file_search="$@"
-	selected_file=$(fzf -e --cycle --color=16 --query="$file_search" --prompt=" Open in app: " --select-1)
-fi
-
-if [ -z $selected_file ] ; then
-#	echo 'No file chosen - Exiting...'
-	exit 1
-else
-	curr_dir=$(pwd)
-	#wal --preview
-	printf "\e[38;5;2m Theme\e[m%s wal is extracting colorscheme from: $selected_file\n"
-	wal -i "$selected_file" -n -q -s -t -e || (echo 'failed to get colors from file' ; exit 1)
-	#sed -n '4,27p' ~/.cache/wal/colors.sh > ~/.termux/color.properties
-	# write to status bar cols
-	sed -i '/status-text-color/d' ~/.tel/configs/theme.conf
-	fg_text_color=$(sed '8q;d' ~/.cache/wal/colors)
-       	echo -e "\nstatus-text-color=$fg_text_color" >> ~/.tel/configs/theme.conf
-
-	printf "\e[38;5;2m Theme\e[m%s setting wallpaper as: $selected_file\n"
-	termux-wallpaper $options "$selected_file" || echo "Couldn't find $selected_file"
-	~/.tel/scripts/wal_cols_termux.sh # copy wal generated cols to ~/.termux/colors.properties
-	am broadcast --user 0 -a com.termux.app.reload_style com.termux > /dev/null 2>&1 # reload cols in termux
-	status_running=$(pgrep -f status_manager.py)
-	if [ ! -z "$status_running" ] ; then
-		~/.tel/scripts/status_manager/toggle_ui.sh
-		sleep 0.7	
-		~/.tel/scripts/status_manager/toggle_ui.sh
-#kill "$(pgrep -f 'status_manager.py')"
-		#pkill -f 'termux-api'
-		#nohup ~/.tel/scripts/status_manager/status_manager.py > /dev/null 2>&1 &
-	fi
-	#printf "\e[38;5;2m Theme\e[m%s TEL must restart for terminal colors to take effect\n"
-	#printf "\e[38;5;2m Theme\e[m%s Restarting TEL...\n"
-	#tel-restart
-fi
-
+main $@
